import {getModels,createViewer} from './viewer.js';
import {layerMarkup,LAYER_COUNT} from './layers.js';
const $=(s,root=document)=>root.querySelector(s),$$=(s,root=document)=>[...root.querySelectorAll(s)];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initial={navigationVersion:3,page:0,scenario:0,sector:0,constructionPhoto:0,sectorReveal:{},process:0,material:'pla',object:'porte-cable',layer:0,observed:[],decision:null,participants:12,machines:4,copies:12,launchMinute:40,duration:'',cooldown:10,checks:[],launched:false,launchAt:0,launchedDuration:0,idea:{job:'',problem:'',object:''},recovery:[],elapsed:0,runningSince:null};
let state={...initial};try{const saved=JSON.parse(sessionStorage.getItem('couche-atelier')||'null');if(saved){state={...initial,...saved};if(saved.navigationVersion!==3){if(!saved.navigationVersion||saved.navigationVersion<2)state.page=state.page>4?state.page-1:state.page;state.page=state.page>=6?state.page-1:state.page;state.navigationVersion=3;}}}catch{}
function save(){try{sessionStorage.setItem('couche-atelier',JSON.stringify(state));}catch{}}
function elapsed(){return state.elapsed+(state.runningSince?Math.max(0,Date.now()-state.runningSince):0);}
const plan=[
 ['Le déclic','00–08',8,'Qu’est-ce que tu ferais ?', 'Consacre environ 2 minutes à chaque image : fais décrire le problème, puis proposer une solution. Crochet : où et pourquoi a-t-il cassé ? Poignée : augmenter l’espace pour les gants en conservant l’écartement des deux vis. Support : essayer le téléphone avec sa coque, observer l’angle et la stabilité. Garde 2 minutes pour comparer remplacer, adapter et tester.','Une imprimante 3D n’est pas la réponse à tout. On commence par le problème.'],
 ['Les usages métiers','08–18',18,'Qu’est-ce que cette pièce change dans le travail ?','Explore les cinq secteurs : environ 2 minutes par cas. Montre la photo, pose la question de départ et laisse le groupe réagir aux questions visibles. Un clic révèle la réponse courte. Pour le luminaire, le dessin situe un embout sans prétendre reproduire le modèle exact.','Ces exemples montrent des pièces et des procédés différents. Fais aussi nommer une limite à vérifier.'],
 ['De l’idée à l’objet','18–25',25,'Comment passes-tu d’un dessin à quelque chose que tu peux toucher ?','Parcours les cinq onglets en 7 minutes. Retrouve la pièce de référence, puis montre le fichier dans le logiciel. Fais comparer des échantillons de PLA, PETG et TPU. Lance le zoom animé sur une paroi : les couches sont grossies pour être visibles. Montre aussi la vraie bobine et la buse à distance.','Le fichier décrit la forme. La préparation définit comment la machine la fabrique.'],
 ['Ton objet','25–30',30,'Quel petit objet te serait vraiment utile ?','Fais choisir entre le porte-câble (1332773) et le porte-GSM (1370706). Note les quantités par objet et par plateau. Avant la séance, ouvre chaque fichier dans le logiciel de préparation et vérifie la machine, la buse, la matière et la durée du plateau complet.','Pas de longue modélisation pendant cet atelier : l’objectif est d’observer, choisir, fabriquer.'],
 ['On lance et on observe','30–50',50,'Que vois-tu sur le plateau ?','Vérifie dans le logiciel la durée du plateau complet et les réglages des machines. Lance les impressions avec le groupe avant la 40e minute, puis fais observer à distance l’adhérence, les déplacements et les traits de matière. Clique chaque observation uniquement quand le groupe l’a réellement vue.','Si la pièce se décolle, préviens l’animateur : ne mets pas les mains dans la machine.'],
 ['Tes choix comptent','50–80',80,'Ces pièces se ressemblent. Se comportent-elles de la même manière ?','Présente les pièces physiques et fais-les comparer. 3 min : observer et prendre en main. 8 min : discuter ensemble matière, épaisseur des parois, remplissage et sens des efforts. Révèle chaque explication après les propositions du groupe. Puis fais choisir une pièce pour un usage et justifier. Fais estimer le coût du filament et demande ce qu’il faudrait aussi compter : machine, énergie, essais et finition. Profite du temps restant pendant l’impression pour rappeler que la résistance, la durée, la matière et la sécurité sont à vérifier pour l’usage prévu.','La résistance ne dépend pas seulement du remplissage. Le calcul ne donne que le prix du filament : une pièce imprimée demande aussi du temps et d’autres ressources. Un prototype doit être testé pour son usage.'],
 ['Une idée à tester','80–95',95,'Quel petit problème autour de toi mériterait un essai ?','5 min en binômes : repère une gêne à la maison, en cours, dans un loisir ou dans un travail envisagé. 5 min : croquis d’un petit objet utile. 5 min : présente la situation, l’objet et un point à mesurer ou vérifier.','L’expérience professionnelle n’est pas nécessaire. Pars d’une situation vécue ou imaginée ; à ce stade, on conçoit un essai.'],
 ['L’objet en main','95–110',110,'Compare la pièce réelle et le modèle : qu’est-ce qui change ?','Confirme la fin sur la machine. Attends le refroidissement prescrit avant retrait. Vérifie les dimensions, l’état et l’usage de la pièce avec chaque participant.','Un retard ne justifie pas de retirer une pièce chaude. Utilise les pièces de secours pour le bilan, puis récupère les impressions terminées.'],
 ['La pièce en main','110–120',120,'Qu’as-tu découvert en passant de l’image à l’objet ?','Fais un tour de table avec la pièce en main : chacun montre un détail, raconte ce qui l’a surpris pendant l’impression et nomme un point à vérifier avant de l’utiliser. Compte 30 à 45 secondes par personne.','La pièce repart avec chaque participant. La démarche reste : observer, choisir, fabriquer et essayer.']
];
const scenarios=[
 {title:'Une pièce<br>cassée.<br><span class="orange">Et maintenant ?</span>',text:'Ton sac est chargé. Le crochet mural vient de casser.',ask:'Qu’est-ce qui s’est passé, selon toi ? Que ferais-tu maintenant ?',photo:'Remplacer.<br>Comprendre la casse.',image:'crochet-casse.jpeg',alt:'Un crochet mural cassé sous un sac chargé de livres. La fixation reste au mur et une main tient le morceau détaché.'},
 {title:'Avec les gants,<br>ça coince.<br><span class="orange">On adapte ?</span>',text:'Tu essaies d’ouvrir un tiroir d’établi avec des gants. Le geste coince.',ask:'Qu’est-ce qui rend ce geste difficile ? Quelle idée te vient ?',photo:'Adapter.<br>Faire de la place.',image:'poignee-tiroir.jpeg',alt:'Une main gantée bute contre une poignée trop proche de la façade en bois. Les deux vis de fixation sont visibles.'},
 {title:'Une idée.<br>Un doute.<br><span class="orange">Un prototype.</span>',text:'Un support vient d’être imprimé. Le téléphone est encore posé à côté.',ask:'À quoi ferais-tu attention en essayant cet objet ?',photo:'Tester.<br>Du dessin à l’usage.',image:'support-telephone.jpeg',alt:'Un support de téléphone blanc imprimé, posé près de son croquis. Le téléphone est à plat à côté, prêt pour un essai.'}
];
const sectors=[
  {
    "name": "Construction",
    "starter": "Observe les deux photos : une maison imprimée en 3D et le dépôt des couches sur un chantier.",
    "image": "construction-beckum.jpg",
    "alt": "Maison de deux étages aux murs courbes et aux lignes de couches visibles, construite par PERI à Beckum en Allemagne.",
    "credit": "Photo : PERI 3D Construction · Beckum, 2020",
    "source": "peri",
    "qa": [
      [
        "",
        "En regardant ces photos, qu’est-ce que tu comprends du travail de la machine ?",
        "La machine dépose de la matière couche après couche pour former les murs. Elle suit un trajet préparé à partir d’un modèle numérique."
      ],
      [
        "",
        "Sur ce chantier, quel serait le rôle des personnes qui travaillent avec elle ?",
        "Préparer le chantier et la machine, surveiller l’impression et vérifier le résultat. Les équipes réalisent aussi les autres travaux nécessaires pour terminer le bâtiment."
      ]
    ],
    "applications": "Maquettes de bâtiments · Éléments de façade · Coffrages pour réaliser des formes particulières"
  },
  {
    "name": "Industrie",
    "starter": "Cette pince imprimée en 3D permet à un robot de déplacer des portes de voiture.",
    "image": "industrie.jpg",
    "alt": "Pince de robot imprimée en 3D dans l’usine BMW de Regensburg, utilisée pour manipuler des portes de voiture.",
    "credit": "Photo : BMW Group",
    "source": "bmw",
    "qa": [
      [
        "",
        "Pourquoi l’usine aurait-elle choisi d’imprimer cette pince ?",
        "Pour fabriquer une forme adaptée à cette tâche. Dans cet exemple, la nouvelle pince est plus légère et plus rigide."
      ],
      [
        "",
        "Si l’usine change de modèle de porte, qu’est-ce que l’impression 3D pourrait lui permettre de faire ?",
        "Modifier le modèle numérique, puis fabriquer et tester une pince adaptée à la nouvelle porte."
      ]
    ],
    "applications": "Prototypes de produits · Outils pour faciliter l’assemblage · Gabarits pour positionner ou percer une pièce"
  },
  {
    "name": "Maintenance",
    "starter": "L’embout d’un luminaire de train n’est plus fabriqué. Sur la photo, tu vois l’ancienne pièce et celle reproduite par impression 3D.",
    "image": "maintenance.jpg",
    "alt": "Deux embouts d’un luminaire de locomotive Class 43 côte à côte : la nouvelle pièce imprimée blanche à gauche et l’ancienne pièce grise à droite.",
    "credit": "Photo : DB ESG · blanc : pièce refaite / gris : pièce d’origine",
    "source": "dbesg",
    "qa": [
      [
        "",
        "Qu’est-ce que la possibilité de refaire cette petite pièce change pour l’entretien du train ?",
        "Elle permet de réparer le luminaire et de continuer à l’utiliser, sans devoir remplacer tout l’ensemble faute de pièce disponible."
      ],
      [
        "",
        "Que faudrait-il vérifier avant d’installer la pièce imprimée ?",
        "Qu’elle se fixe correctement, maintient les éléments prévus et convient aux conditions d’utilisation dans le train."
      ]
    ],
    "applications": "Boutons de commande introuvables · Clips et caches de remplacement · Poignées adaptées à un équipement"
  },
  {
    "name": "Santé",
    "starter": "Le chirurgien dispose des images du rein de son patient, sur lequel se trouve une tumeur. Il fait aussi fabriquer une copie imprimée en 3D.",
    "image": "sante.jpg",
    "alt": "Modèle anatomique imprimé d’un rein avec tumeur et vaisseaux, publié dans un travail scientifique antérieur de la même équipe.",
    "credit": "Photo : Gómez Ciriza et coll., 2019 · autre travail de l’équipe",
    "source": "rivero",
    "qa": [
      [
        "",
        "À quoi cette copie pourrait-elle lui servir avant l’opération ?",
        "À observer le rein sous différents angles, repérer la position de la tumeur par rapport aux vaisseaux et préparer son geste avec l’équipe."
      ]
    ],
    "applications": "Prothèses dentaires · Orthèses sur mesure pour soutenir un membre · Modèles anatomiques pour la formation"
  },
  {
    "name": "Design",
    "starter": "Cette chaussure Adidas est entièrement imprimée en 3D et commercialisée pour être portée.",
    "image": "design.jpg",
    "alt": "Chaussure Adidas Climacool à structure ajourée imprimée en 3D.",
    "credit": "Photo : adidas",
    "source": "adidas",
    "qa": [
      [
        "",
        "Quelle matière choisirais-tu pour fabriquer cette chaussure ? Pourquoi ?",
        "Une matière qui puisse se déformer pour accompagner le pied et résister à un usage répété. Sa tenue à l’usure et son confort doivent ensuite être testés."
      ]
    ],
    "applications": "Bijoux · Luminaires · Montures de lunettes"
  }
];
const objects={
 'porte-cable':{name:'Le porte-câble',goal:'Tes câbles à portée de main.',number:'1332773',image:'choix-porte-cable.png',alt:'Porte-câble imprimé en 3D, aux ouvertures arrondies, reprenant la pièce de la page précédente.',question:'Tes câbles passent-ils dans les ouvertures ? Que faut-il vérifier pour qu’ils tiennent ?',file:null},
 'porte-gsm':{name:'Le porte-GSM',goal:'Un support qui suit tes clés.',number:'1370706',image:'choix-porte-gsm-pliant.png',alt:'Porte-GSM pliant noir et orange : replié avec un trousseau de clés au premier plan, et déplié pour soutenir un téléphone derrière.',question:'Ton GSM tient-il avec sa coque ? Comment vérifier la stabilité et l’angle de l’écran ?',file:null}
};
if(!objects[state.object])state.object='porte-cable';
const sources={
 peri:{author:'PERI 3D Construction',title:'Maison individuelle imprimée à Beckum',url:'https://www.peri3dconstruction.com/en/einfamilienhaus-in-beckum',date:'2020',note:'Maison de deux étages aux murs arrondis. Photo de la maison publiée par PERI. Certains éléments ont été préfabriqués séparément.'},
 bmw:{author:'BMW Group',title:'3D printed robot grippers in Regensburg',url:'https://www.press.bmwgroup.com/global/article/detail/T0442351EN/bmw-group-e',date:'23 mai 2024',note:'Pince pour la manipulation de portes à l’usine de Regensburg ; photo publiée par BMW Group.'},
 dbesg:{author:'DB ESG',title:'Additive Manufacture of Lighting Unit End Caps',url:'https://dbesg.deutschebahn.com/esg/case-studies/Additive-Manufacture-Lighting-Unit-End-Caps_angel-trains-8930902',date:'Octobre 2021',note:'Cas des locomotives Class 43 : la pièce blanche imprimée est photographiée à côté de l’embout d’origine gris. L’embout obsolète a été reproduit puis son ajustement et sa fonction vérifiés avant la fabrication de 50 exemplaires. Le même article présente un autre projet, sur Class 153, où un embout a été redessiné pour renforcer les zones de rupture.'},
 rivero:{author:'Rivero Belenchón et coll.',title:'Essai randomisé de modèles rénaux imprimés pour la préparation opératoire',url:'https://pubmed.ncbi.nlm.nih.gov/39836858/',date:'2025',note:'66 patients ; moins de complications dans le groupe avec modèle, durée moyenne similaire. Photo illustrative issue d’un autre travail de l’équipe (2019).'},
 adidas:{author:'adidas',title:'3D Printed Climacool — présentation du modèle',url:'https://news.adidas.com/innovations/3d-printed-climacool--a-shoe-that-pushes-boundaries-of-design-innovation/s/10c1b774-a96e-4050-bff6-339ec3ef04b1',date:'2024',note:'Chaussure Climacool entièrement imprimée en 3D et structure ajourée ; photo du produit publiée par adidas.'},
 pla:{author:'Prusa Research',title:'PLA — propriétés et usages',url:'https://help.prusa3d.com/article/pla_2062',note:'Facilité d’impression, rigidité, prototypes et limites face aux chocs et à la chaleur.'},
 petg:{author:'Prusa Research',title:'PETG — propriétés et usages',url:'https://help.prusa3d.com/article/petg_2059',note:'Pièces fonctionnelles, résistance à la casse et limites d’impression.'},
 tpu:{author:'Prusa Research',title:'Matériaux flexibles — dont le TPU',url:'https://help.prusa3d.com/article/flexible-materials_2057',note:'Souplesse, protections, vitesses et réglages adaptés à chaque référence.'},
 conception:{author:'Prusa Research',title:'Modeling with 3D printing in mind',url:'https://help.prusa3d.com/article/modeling-with-3d-printing-in-mind_164135',note:'Orientation, supports, ajustements et limites de conception.'},
 industrie:{author:'Prusa Research',title:'3D printing for manufacturing',url:'https://www.prusa3d.com/p/3d-printing-for-manufacturing/',note:'Prototypes, aides à la fabrication et pièces de remplacement.'},
 architecture:{author:'Prusa Research',title:'3D printing for architects and designers',url:'https://www.prusa3d.com/applications/3d-printing-for-architects-and-designers_231948/',note:'Maquettes et prototypes pour le design.'},
 sante:{author:'Prusa Research',title:'3D printing for healthcare',url:'https://www.prusa3d.com/applications/3d-printing-for-healthcare_232354/',note:'Modèles anatomiques et applications professionnelles de santé.'},
 securite:{author:'NIOSH / CDC',title:'Approaches to Safe 3D Printing — A Guide for Makerspace Users',url:'https://www.cdc.gov/niosh/docs/2024-103/default.html',date:'Novembre 2023',note:'Précautions pour l’impression 3D dans les ateliers, écoles et petits espaces de travail.'}
};
let viewer=null,playTimer=null,renderToken=0,modalOpener=null;
function kicker(i){return `<div class="kicker-line"><div class="eyebrow">${String(i+1).padStart(2,'0')} / ${plan[i][0]} <span class="time">${plan[i][1]} MIN</span></div><span class="label">Observer. Choisir. Fabriquer.</span></div>`;}
function viewHTML(id='model-view'){return `<div class="viewer-wrap"><canvas id="${id}" tabindex="0" aria-label="Modèle 3D manipulable. Glisse horizontalement ou utilise les flèches gauche et droite.">Modèle 3D de l’objet sélectionné.</canvas><div class="viewer-tools"><button data-view="rotate" aria-label="Faire tourner l’objet">↻</button><button data-view="in" aria-label="Agrandir l’objet">+</button><button data-view="out" aria-label="Réduire l’objet">−</button></div><span class="viewer-hint">Glisse pour tourner · vue à l’échelle relative</span></div>`;}
function screen0(){const s=scenarios[state.scenario];return `${kicker(0)}<div class="hero"><div class="hero-copy"><div><h1>${s.title}</h1><p class="lede">${s.text}</p><div class="scenario-tabs">${['Remplacer','Adapter','Tester'].map((x,i)=>`<button class="pill" data-scenario="${i}" aria-pressed="${state.scenario===i}">${x}</button>`).join('')}</div></div><div class="challenge"><span class="symbol" aria-hidden="true">?</span><p><strong>Et toi, tu ferais quoi ?</strong>${s.ask}</p></div></div><figure class="hero-visual scenario-visual" style="margin:0"><img src="assets/${s.image}" alt="${escape(s.alt)}"><span class="photo-label">DE L’IDÉE À LA MATIÈRE</span><figcaption class="photo-caption"><strong>${s.photo}</strong><span>Gros plan illustratif<br>Image générée</span></figcaption></figure></div>`;}
const constructionPhotos=[
 {image:'construction-beckum.jpg',alt:'Maison de deux étages aux murs courbes et aux lignes de couches visibles, construite par PERI à Beckum.',label:'La maison terminée',credit:'Photo : PERI 3D Construction · Beckum, 2020'},
 {image:'construction-depot.jpeg',alt:'Gros plan d’une tête d’impression déposant de la matière sur un mur courbe. Les couches superposées sont nettement visibles.',label:'Le dépôt des couches',credit:'Photo fournie · dépôt couche par couche'}
];
function casePhotoHTML(c){if(state.sector!==0)return `<figure class="case-photo"><img src="assets/${c.image}" alt="${escape(c.alt)}"><figcaption><span>${c.credit}</span><span>0${state.sector+1} / 05</span></figcaption></figure>`;const index=state.constructionPhoto===1?1:0;const p=constructionPhotos[index];return `<div class="case-carousel" role="region" aria-roledescription="carrousel" aria-label="Photos de construction imprimée"><figure class="case-photo"><img class="construction-slide" src="assets/${p.image}" alt="${escape(p.alt)}"><figcaption><span>${p.credit}</span><span aria-live="polite">${index+1} / 2</span></figcaption></figure><div class="construction-controls"><button class="nav-arrow" data-construction="prev" aria-label="Photo précédente">←</button><div class="construction-tabs">${constructionPhotos.map((photo,i)=>`<button data-construction="${i}" aria-pressed="${index===i}">${photo.label}</button>`).join('')}</div><button class="nav-arrow" data-construction="next" aria-label="Photo suivante">→</button></div></div>`;}
function screen1(){const c=sectors[state.sector];return `${kicker(1)}<div class="section-head"><h2>Ça sert à quoi,<br><span class="orange">dans la vraie vie ?</span></h2><p class="lede">Choisis un domaine.<br>Observe, propose, puis vérifie.</p></div><div class="tabbar">${sectors.map((s,i)=>`<button class="tab" data-sector="${i}" aria-pressed="${state.sector===i}">${s.name}</button>`).join('')}</div><div class="case-layout"><div>${casePhotoHTML(c)}${state.sector===2?`<div class="luminaire-context"><svg viewBox="0 0 560 105" role="img" aria-label="Schéma de principe d’un luminaire fluorescent allongé avec un embout à son extrémité droite."><rect x="26" y="29" width="425" height="51" rx="9" fill="#dce1dc" stroke="#6f7771" stroke-width="3"/><rect x="49" y="39" width="384" height="31" rx="7" fill="#f7f5de"/><rect x="451" y="25" width="45" height="59" rx="7" fill="#ff5b2d"/><path d="M520 18 L486 31" stroke="#ff5b2d" stroke-width="3"/><text x="312" y="101" font-size="15" fill="#3f4841">luminaire</text><text x="465" y="17" font-size="15" fill="#3f4841">embout</text></svg><p>La pièce se place à l’extrémité d’un luminaire fluorescent. Schéma de principe : le modèle exact n’est pas identifié.</p></div>`:''}</div><div class="case-panel"><span class="case-domain">${c.name.toUpperCase()} · CAS RÉEL</span><h3>${c.starter}</h3><p class="case-applications"><strong>D’autres usages dans ce secteur</strong><span>${c.applications}</span></p><p class="case-hint">Propose ta réponse, puis touche une question.</p><div class="case-questions">${c.qa.map(([,question,answer],i)=>{const revealed=!!state.sectorReveal?.[`v2-${state.sector}-${i}`];return `<button class="case-question" data-case="${i}" aria-expanded="${revealed}"><span class="case-question-top"><strong>${question}</strong><span aria-hidden="true">${revealed?'−':'+'}</span></span>${revealed?`<span class="case-question-body case-answer">${answer}</span>`:''}</button>`;}).join('')}</div><button class="text-link" data-source="${c.source}">Voir la source du cas ↗</button><p class="micro muted">Touche une question pour afficher ou masquer la réponse.</p></div></div>`;}
const process=[
 ['Le modèle 3D','Avant l’objet, il y a sa forme dans un fichier. Tu peux créer ce modèle, le modifier ou en récupérer un.','Le fichier décrit la forme et les dimensions.','Qu’est-ce que tu voudrais mesurer sur cette pièce ?'],
 ['La préparation','Le logiciel découpe la forme en couches et prépare les déplacements de la buse. Tu règles la position, la matière et la machine.','Après le choix de matière, tu revérifies les réglages et la durée du plateau complet.','Avant de lancer, comment savoir si tout sera fini à temps ?'],
 ['Les matériaux','','','Pour cette pièce, tu voudrais une matière rigide ou souple ? Pourquoi ?'],
 ['Le filament chauffé','Le fil de plastique entre dans la tête chauffante. Il fond, puis sort par un petit embout : la buse.','La buse et le plateau peuvent brûler : tu observes à distance.','Comment ce fil peut-il devenir une pièce ?'],
 ['Couche par couche','La buse dépose un trait de matière, puis recommence au-dessus. Les couches s’ajoutent et la pièce prend de la hauteur.','Ce zoom montre le principe sur une paroi. Les couches sont grossies et le mouvement accéléré.','Observe : qu’est-ce qui change quand la buse passe à la couche suivante ?']
];
const materials={
 pla:{name:'PLA',tag:'Rigide · pour commencer',text:'Facile à imprimer. Pratique pour essayer une forme ou fabriquer une maquette.',example:'Exemple : un premier prototype.',limit:'Il supporte mal la chaleur et peut casser sous un choc.'},
 petg:{name:'PETG',tag:'Moins cassant',text:'Généralement moins cassant que le PLA et plus résistant à la chaleur. Utile pour des pièces que tu manipules.',example:'Exemple : un support ou une fixation légère.',limit:'Il peut laisser de petits fils. Les réglages et la tenue de la pièce restent à vérifier.'},
 tpu:{name:'TPU',tag:'Souple · se déforme',text:'Il se plie et reprend sa forme. Sa souplesse varie selon la référence choisie.',example:'Exemple : une protection ou un patin souple.',limit:'Il demande des réglages adaptés et une impression souvent plus lente.'}
};
function referenceHTML(){return `<figure class="process-reference"><img src="assets/piece-reference.png" alt="Pièce grise de référence : une forme allongée avec des boucles arrondies et des fentes, dont les couches d’impression sont visibles." width="1448" height="1086"><figcaption>La pièce de référence · image générée</figcaption></figure>`;}
function heatedHTML(){return `<div class="heated-diagram"><svg viewBox="0 0 600 350" role="img" aria-label="Le filament entre par le haut, fond dans la zone chauffante et sort par la buse pour être déposé sur le plateau."><path d="M265 26V142" stroke="#ff5b2d" stroke-width="10" fill="none"/><path d="m255 89 10 12 10-12" stroke="#171918" stroke-width="3" fill="none"/><rect x="220" y="140" width="90" height="65" rx="7" fill="#171918"/><path d="M249 205h32l-12 32h-8z" fill="#8d9286"/><path d="M265 239v43H422" stroke="#ff5b2d" stroke-width="7" fill="none"/><path d="M120 290h355" stroke="#6d786a" stroke-width="5"/><g font-family="Arial,sans-serif" font-size="18" fill="#171918"><text x="300" y="55">Filament</text><text x="334" y="179">Zone chauffante</text><text x="150" y="230">Buse</text><text x="302" y="326">Matière déposée</text></g></svg><p>Le plastique est chauffé avant d’être déposé.</p></div>`;}
function layersHTML(){return `<div class="layer-demo"><div class="layer-demo-head"><img src="assets/piece-reference.png" alt="" width="96" height="72"><div><strong>Zoom sur une paroi</strong><span>Couches grossies pour les voir</span></div></div><div id="layer-drawing">${layerMarkup(state.layer)}</div></div><div class="range-box"><label class="range-label" for="layers"><span>Fais avancer l’impression</span><output id="layer-value">${Math.floor(state.layer/100*LAYER_COUNT)} / ${LAYER_COUNT} couches</output></label><input id="layers" type="range" min="0" max="100" step="0.2" value="${state.layer}" aria-label="Avancement de la démonstration des couches"><div class="layer-actions"><button class="primary dark" id="play-layers">▷ ${state.layer>=100?'Rejouer':'Animer les couches'}</button><button class="pill" id="reset-layers">Recommencer</button></div><p class="small muted layer-status" id="layer-status">${state.layer>=100?'La paroi est terminée.':'Une ligne se dépose, puis la suivante se forme au-dessus.'}</p></div>`;}
function materialHTML(){const selected=materials[state.material]||materials.pla;return `<div class="material-choice" aria-label="Matériaux proposés dans l’atelier">${Object.entries(materials).map(([key,m])=>`<button data-material="${key}" aria-pressed="${state.material===key}"><strong>${m.name}</strong><span>${m.tag}</span></button>`).join('')}</div><div class="material-detail"><p class="lede">${selected.text}</p><p class="body">${selected.example}</p><p class="notice">${selected.limit}</p></div><p class="small muted">Ce sont les trois matières proposées dans l’atelier. Il en existe d’autres pour d’autres usages : chaleur, extérieur, usure…</p><button class="text-link" data-source="materiaux">Comparer les propriétés et les limites ↗</button>`;}
function screen2(){state.process=Math.max(0,Math.min(4,Number(state.process)||0));state.layer=Math.max(0,Math.min(100,Number(state.layer)||0));if(!materials[state.material])state.material='pla';const p=process[state.process];return `${kicker(2)}<div class="section-head"><h2>Un fichier.<br><span class="orange">Puis de la matière.</span></h2><p class="lede">Une même pièce.<br>De la forme aux couches.</p></div><div class="steps process-steps" aria-label="De l’idée à l’objet">${process.map((p,i)=>`<button class="step-btn" data-process="${i}" aria-pressed="${state.process===i}"><span>0${i+1}</span>${p[0]}</button>`).join('')}</div><div class="split process-layout"><div>${state.process===3?heatedHTML():state.process===4?layersHTML():referenceHTML()}${state.process===1?'<div class="preparation-checks"><span>Position de la pièce</span><span>Choix des réglages</span><span>Durée vérifiée</span></div>':''}</div><div class="process-copy"><span class="number">ÉTAPE 0${state.process+1}</span><h3>${p[0]}</h3>${state.process===2?materialHTML():`<p class="lede">${p[1]}</p><p class="notice">${p[2]}</p>`}<div class="challenge"><span class="symbol" aria-hidden="true">?</span><p>${p[3]}</p></div>${state.process===1?'<button class="text-link" data-source="conception">Comprendre la préparation ↗</button>':''}</div></div>`;}
function screen3(){const o=objects[state.object];return `${kicker(3)}<div class="section-head"><h2>Deux modèles.<br><span class="orange">Lequel est pour toi ?</span></h2><p class="lede">Choisis celui qui te serait utile.<br>On vérifie ensuite le temps d’impression.</p></div><div class="print-choices" aria-label="Choisis ton objet">${Object.entries(objects).map(([id,item],i)=>`<button class="print-choice" data-object="${id}" aria-pressed="${id===state.object}"><div class="print-choice-photo"><img src="assets/${item.image}" alt="${escape(item.alt)}" width="1448" height="1086"><span class="print-choice-state">${id===state.object?'✓ Ton choix':'Choisir ce modèle'}</span></div><div class="print-choice-caption"><span class="print-choice-index">0${i+1}</span><div><strong>${item.name}</strong><span>${item.goal}</span></div><span class="print-choice-ref">N° ${item.number}</span></div></button>`).join('')}</div><div class="print-selection"><div class="challenge"><span class="symbol" aria-hidden="true">?</span><p><strong>Avant de fabriquer</strong>${o.question}</p></div><div class="print-file"><div><span class="small muted">${o.name} · N° d’impression</span><strong class="print-number">${o.number}</strong></div>${o.file?`<a class="primary dark" href="${escape(o.file)}" download>Télécharger le 3MF ↓</a>`:''}</div></div><p class="print-choice-note">Images générées d’illustration. La durée sera vérifiée dans le logiciel, avec le fichier 3MF et les réglages de l’atelier.</p>`;}
function screen4(){const obs=[['Ça accroche.','La première couche reste sur le plateau. Si elle se décolle, préviens l’animateur.'],['Ça suit un trajet.','La tête dépose certains traits et se déplace aussi sans déposer.'],['Ça prend du volume.','Les nouveaux passages se superposent aux précédents.']];return `${kicker(4)}<div class="section-head"><h2>On lance.<br><span class="orange">Et on observe.</span></h2><p class="lede">Lance l’impression avec l’animateur.<br>Puis repère les premiers gestes de la machine.</p></div><div class="split"><figure class="first-layers-photo"><img src="assets/premieres-couches.png" alt="Illustration : une buse d’imprimante dépose les premières lignes de plastique orange sur un plateau texturé."><figcaption>Les premiers traits de matière · image générée</figcaption></figure><div class="observe-list">${obs.map((o,i)=>`<button class="observe" data-observe="${i}" aria-pressed="${state.observed.includes(i)}"><strong>${state.observed.includes(i)?'✓ ':''}${o[0]}</strong><span>${o[1]}</span></button>`).join('')}<p class="small muted">Observation à distance : ne touche ni la buse, ni le plateau, ni les parties en mouvement.</p></div></div>`;}
function screen5(){const points=[
 ['La matière','Rigide ou souple : qu’est-ce que tu sens ?','Compare les échantillons de PLA, PETG et TPU. La matière choisie compte, mais la forme et les réglages aussi.'],
 ['Les parois','Le contour est-il fin ou épais ?','Les parois forment l’enveloppe de la pièce. Compare leur épaisseur sur les échantillons présentés.'],
 ['Le remplissage','À l’intérieur : plein ou ajouré ?','Le remplissage est la structure à l’intérieur. Observe la quantité de matière et la façon dont elle est répartie.'],
 ['Le sens des efforts','Dans quel sens la pièce va-t-elle être tirée, poussée ou pliée ?','Repère les couches : une pièce imprimée ne résiste pas forcément de la même façon dans toutes les directions.']
 ];return `${kicker(5)}<div class="section-head"><h2>La différence ?<br><span class="orange">Prends-la en main.</span></h2><p class="lede">Compare les pièces de l’animateur.<br>Qu’est-ce qui change d’une pièce à l’autre ?</p></div><div class="sample-comparison"><aside class="sample-mission"><span class="eyebrow">PIÈCES EN MAIN</span><h3>Observe.<br>Compare.<br>Explique.</h3><p>Regarde les couches, les bords et l’intérieur visible. Compare le poids et la souplesse selon les consignes de l’animateur.</p><div class="sample-prompt">Pour quel usage choisirais-tu cette pièce ?<br><strong>Qu’est-ce qui te fait dire ça ?</strong></div></aside><div class="sample-topics">${points.map(([title,q,answer],i)=>`<details class="sample-topic"><summary><span class="sample-topic-label">0${i+1} · ${title}</span><strong>${q}</strong><span class="sample-reveal">Propose, puis touche pour comprendre <span aria-hidden="true">+</span></span></summary><p>${answer}</p></details>`).join('')}</div></div><div class="sample-takeaway"><strong>Une pièce adaptée, c’est un ensemble de choix.</strong><p>Matière, parois, remplissage et sens des efforts : relie-les à ce que la pièce devra faire.</p></div><div class="cost"><strong>Et le coût ?</strong><label>Masse de la pièce <input id="mass" type="number" min="0" step="0.1" value="5"> g</label><label>Prix du filament <input id="price" type="number" min="0" step="0.1" value="25"> €/kg</label><output id="cost">0,13 €</output><span class="micro muted">Filament seulement · il faut aussi compter la machine, l’énergie, les essais et la finition.</span></div><p class="small muted" style="margin-top:14px">Avant d’utiliser une pièce, vérifie aussi sa résistance, le temps de fabrication, la matière et la sécurité pour l’usage prévu.</p><button class="text-link" data-source="conception">Repères sur la conception ↗</button>`;}
function screen7(){return `${kicker(6)}<div class="section-head"><h2>Une gêne.<br><span class="orange">Une idée à tester.</span></h2><p class="lede">Chez toi, en cours, dans un loisir<br>ou dans un travail que tu imagines.</p></div><div class="split"><div class="workshop-note"><span class="micro">MISSION · 15 MINUTES</span><h2>Repère.<br>Dessine.<br>Raconte.</h2><p class="body">En binôme, trouve un petit problème. Dessine un objet qui pourrait aider. Puis présente ton idée en 30 secondes.</p></div><div class="idea-form"><label>Dans quelle situation ?<input class="wide-input" data-idea="job" maxlength="80" placeholder="Ex. quand je range mon bureau" value="${escape(state.idea.job)}"></label><label>Qu’est-ce qui te gêne ?<input class="wide-input" data-idea="problem" maxlength="160" placeholder="Ex. mon câble tombe derrière la table" value="${escape(state.idea.problem)}"></label><label>Quel petit objet pourrais-tu essayer ?<input class="wide-input" data-idea="object" maxlength="160" placeholder="Ex. un guide-câble pour le bord de la table" value="${escape(state.idea.object)}"></label><p class="pitch" id="pitch" aria-live="polite"></p><p class="small muted">À dire aussi : qu’est-ce qu’il faudrait mesurer ou vérifier avant de fabriquer ?</p></div></div>`;}
function updatePitch(){if(!$('#pitch'))return;$('#pitch').textContent=state.idea.job&&state.idea.problem&&state.idea.object?`Situation : ${state.idea.job}. Problème : ${state.idea.problem}. Objet à tester : ${state.idea.object}.`:'Choisis une situation, un problème et un objet à tester.';}
function screen8(){return `${kicker(7)}<div class="section-head"><h2>De l’écran<br><span class="orange">à ta main.</span></h2><p class="lede">L’animateur confirme la fin<br>et le refroidissement sur la machine.</p></div><div class="recovery"><article><span>01</span><h3>Laisse refroidir.</h3><p>Attends l’accord de l’animateur. Une pièce terminée peut encore être chaude.</p></article><article><span>02</span><h3>Observe ta pièce.</h3><p>Repère les couches, compare les dimensions et regarde la face posée sur le plateau.</p></article><article><span>03</span><h3>Essaie son usage.</h3><p>Teste sans forcer. Est-ce adapté ? Que changerais-tu à la prochaine version ?</p></article></div><div class="checks" style="margin-top:25px">${['Fin et refroidissement vérifiés par l’animateur.','Chacun a récupéré sa pièce et essayé son usage.'].map((t,i)=>`<label class="check"><input type="checkbox" data-recovery="${i}" ${state.recovery.includes(i)?'checked':''}><span>${t}</span></label>`).join('')}</div><p class="notice">Un imprévu ? Utilise un exemplaire préparé à l’avance pour le bilan. L’animateur organise la récupération de la pièce dès qu’elle est prête.</p>`;}
function screen9(){return `${kicker(8)}<div class="finish closing"><div><span class="finish-tag">L’OBJET EN MAIN · DERNIER TOUR DE PAROLE</span><h1>De la bobine<br>à ta main.<br><span class="orange">Qu’as-tu découvert ?</span></h1><p class="lede">Regarde ta pièce. Repense à sa fabrication. Raconte ce que l’objet réel t’a appris.</p><button class="text-link" data-source="all">Sources et repères ↗</button></div><div class="closing-card"><span class="eyebrow">30 SECONDES POUR PARTAGER</span><ol><li><span>01</span><strong>Montre un détail</strong><p>Une couche, une forme, une face ou un ajustement.</p></li><li><span>02</span><strong>Raconte une surprise</strong><p>Qu’as-tu remarqué pendant la fabrication ?</p></li><li><span>03</span><strong>Dis ce que tu vérifierais</strong><p>Avant d’utiliser ta pièce pour de bon.</p></li></ol></div></div>`;}
const screens=[screen0,screen1,screen2,screen3,screen4,screen5,screen7,screen8,screen9];
function toggle(arr,n){return arr.includes(n)?arr.filter(x=>x!==n):[...arr,n];}
async function render(focus=false){const token=++renderToken;viewer?.dispose();viewer=null;clearInterval(playTimer);playTimer=null;state.page=Math.max(0,Math.min(8,Number(state.page)||0));const p=state.page;$('#stage').innerHTML=screens[p]();$('#stage').classList.remove('fade-in');void $('#stage').offsetWidth;$('#stage').classList.add('fade-in');$('#page-number').textContent=`${String(p+1).padStart(2,'0')} / 09`;$('#chapter-name').textContent=plan[p][0];$('#progress').style.width=`${(p+1)/9*100}%`;$('#prev').disabled=p===0;$('#next').disabled=p===8;$('#next').innerHTML=p===8?'Atelier terminé ✓':`${plan[p+1][0]} <span aria-hidden="true">→</span>`;$('#dots').innerHTML=plan.map((s,i)=>`<button class="dot" data-go="${i}" aria-label="Étape ${i+1} : ${s[0]}" ${i===p?'aria-current="step"':''}></button>`).join('');$('#announcement').textContent=`Étape ${p+1} sur 9 : ${plan[p][0]}`;bind();if(p===6)updatePitch();save();if(focus){$('#stage').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}const canvas=$('#model-view');if(canvas){try{const m=await getModels();if(token!==renderToken)return;viewer=createViewer(canvas,m.enrouleur,{progress:1});}catch{if(token===renderToken)canvas.parentElement.innerHTML='<p class="notice">Le modèle de démonstration ne peut pas s’afficher. Recharge la page.</p>';}}
}
function go(n){if(!Number.isInteger(n)||n<0||n>8)return;document.body.classList.remove('intro-active');state.page=n;history.replaceState(null,'',`#etape-${n+1}`);render(true);}
function bind(){
 $$('[data-construction]').forEach(b=>b.onclick=()=>{const value=b.dataset.construction;state.constructionPhoto=/^[01]$/.test(value)?Number(value):state.constructionPhoto===1?0:1;render().then(()=>$(`[data-construction="${value}"]`)?.focus({preventScroll:true}));});
 $('.case-carousel')?.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();e.stopPropagation();$(`[data-construction="${e.key==='ArrowLeft'?'prev':'next'}"]`)?.click();}});

 $$('[data-scenario]').forEach(b=>b.onclick=()=>{state.scenario=+b.dataset.scenario;render();});$$('[data-sector]').forEach(b=>b.onclick=()=>{state.sector=+b.dataset.sector;render();});$$('[data-case]').forEach(b=>b.onclick=()=>{const i=+b.dataset.case,key=`v2-${state.sector}-${i}`;state.sectorReveal={...state.sectorReveal,[key]:state.sectorReveal?.[key]?0:1};render().then(()=>{const next=$(`[data-case="${i}"]`);next?.focus({preventScroll:true});});});$$('[data-process]').forEach(b=>b.onclick=()=>{state.process=+b.dataset.process;render().then(()=>$(`[data-process="${state.process}"]`)?.focus({preventScroll:true}));});$$('[data-material]').forEach(b=>b.onclick=()=>{state.material=b.dataset.material;render().then(()=>$(`[data-material="${state.material}"]`)?.focus({preventScroll:true}));});$$('[data-object]').forEach(b=>b.onclick=()=>{state.object=b.dataset.object;render().then(()=>$(`[data-object="${state.object}"]`)?.focus({preventScroll:true}));});
 $$('[data-go]').forEach(b=>b.onclick=()=>go(+b.dataset.go));$$('[data-source]').forEach(b=>b.onclick=()=>showSources(b.dataset.source));
 $$('[data-view]').forEach(b=>b.onclick=()=>b.dataset.view==='rotate'?viewer?.rotate():viewer?.zoom(b.dataset.view==='in'?.15:-.15));
 $('#layers')?.addEventListener('input',e=>{stopLayerAnimation();state.layer=+e.target.value;updateLayerDemo();save();});
 $('#play-layers')?.addEventListener('click',()=>{if(playTimer){stopLayerAnimation();save();}else startLayerAnimation();});
 $('#reset-layers')?.addEventListener('click',()=>{stopLayerAnimation();state.layer=0;updateLayerDemo();save();});
 $$('[data-observe]').forEach(el=>el.onclick=()=>{state.observed=toggle(state.observed,+el.dataset.observe);render();});$$('[data-decision]').forEach(el=>el.onclick=()=>{state.decision=el.dataset.decision;render();});
 ['mass','price'].forEach(id=>$('#'+id)?.addEventListener('input',()=>{const m=+$('#mass').value,p=+$('#price').value;$('#cost').textContent=m>=0&&p>=0&&$('#mass').value!==''&&$('#price').value!==''?(m*p/1000).toLocaleString('fr-BE',{style:'currency',currency:'EUR'}):'—';}));
 $$('[data-idea]').forEach(el=>el.oninput=()=>{state.idea={...state.idea,[el.dataset.idea]:el.value};save();updatePitch();});$$('[data-recovery]').forEach(el=>el.onchange=()=>{state.recovery=toggle(state.recovery,+el.dataset.recovery);save();});
}
function stopLayerAnimation(){clearInterval(playTimer);playTimer=null;const b=$('#play-layers');if(b){b.textContent=state.layer>=100?'▷ Rejouer':'▷ Animer les couches';b.setAttribute('aria-pressed','false');}}
function updateLayerDemo(){const drawing=$('#layer-drawing');if(!drawing)return;drawing.innerHTML=layerMarkup(state.layer);$('#layers').value=state.layer;if(!playTimer)$('#play-layers').textContent=state.layer>=100?'▷ Rejouer':'▷ Animer les couches';const n=Math.floor(state.layer/100*LAYER_COUNT+1e-8);$('#layer-value').textContent=`${n} / ${LAYER_COUNT} couches`;$('#layer-status').textContent=state.layer>=100?'La paroi est terminée.':state.layer>0?`Couche ${n+1} : la buse dépose la matière.`:'Une ligne se dépose, puis la suivante se forme au-dessus.';}
function startLayerAnimation(){if(state.layer>=100)state.layer=0;clearInterval(playTimer);$('#play-layers').textContent='Ⅱ Pause';$('#play-layers').setAttribute('aria-pressed','true');updateLayerDemo();playTimer=setInterval(()=>{if(!$('#layer-drawing')){stopLayerAnimation();return;}state.layer=Math.min(100,Math.round((state.layer+.2)*10)/10);updateLayerDemo();if(state.layer===100){stopLayerAnimation();save();}},40);}
function openModal(kicker,html){modalOpener=document.activeElement;$('#modal-kicker').textContent=kicker;$('#modal-body').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();$('#modal').scrollTop=0;$('#close-modal').focus();}
function closeModal(){$('#modal').close();modalOpener?.focus?.();}
function showSources(which){const keys=which==='all'?Object.keys(sources):which==='materiaux'?['pla','petg','tpu']:[which];openModal('SOURCES & REPÈRES',`<h2 class="modal-title">Pour aller vérifier.</h2><p class="small">Sources consultées le 27 septembre 2026. Les résultats d’un cas précis ne garantissent pas le même effet ailleurs.</p><div class="sources">${keys.map(k=>{const s=sources[k];return `<a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.title} ↗</a><p class="small muted">${s.author} · ${s.date||'Sans date affichée'}<br>${s.note}</p>`;}).join('')}</div><div class="guide-block" style="margin-top:24px"><h3>À propos des images</h3><p>Les trois situations de départ, le visuel des premières couches, la pièce de référence de la page 3 et les deux visuels de choix de la page 4 sont des images générées d’illustration. La pièce de référence reprend la photo fournie ; ce visuel ne constitue pas un fichier 3D ni un relevé de dimensions. La photo du dépôt des couches dans la construction a été fournie par l’animateur ; son auteur et son chantier ne sont pas identifiés ici. Les autres photos des usages métiers proviennent des organismes et travaux cités ; le modèle anatomique photographié est issu d’un autre travail de la même équipe.</p></div>`);}
function showGuide(){const p=plan[state.page];openModal('GUIDE ANIMATEUR',`<h2 class="modal-title">${p[0]} <span class="orange">${p[1]} min</span></h2><p class="guide-quote">« ${p[3]} »</p><div class="guide-block"><h3>À faire maintenant</h3><p>${p[4]}</p></div><div class="guide-block"><h3>À faire comprendre</h3><p>${p[5]}</p></div><div class="guide-block"><h3>Avant l’arrivée du groupe</h3><ul><li>Teste les deux fichiers 3MF avec les machines, buses et filaments réellement utilisés. Vérifie leurs usages et prépare des exemplaires de secours.</li><li>Prépare les profils, les plateaux et leur répartition. Le groupe doit pouvoir repartir avec une pièce par personne.</li><li>Prévois des fichiers déjà ouverts et des échantillons de PLA, PETG et TPU. Vérifie la compatibilité et le profil de chaque filament réellement utilisé, les consignes du fabricant et une ventilation adaptée. N’ajoute pas de longue modélisation.</li><li>À 40 min au plus tard, vise un planning d’impression de 50 min maximum, chauffe et changements compris, puis 10 min de marge et 10 min de refroidissement. Prolonge le refroidissement si le fabricant l’exige et réduis d’autant le temps d’impression.</li></ul></div><div class="guide-block"><h3>Piloter l’atelier</h3><p>Les flèches et les repères en bas de page donnent accès à chaque écran. Les flèches du clavier fonctionnent aussi. Les interactions fonctionnent au clic et au toucher. Aucune étape n’avance toute seule. Le chrono mesure l’atelier ; il ne lit pas l’état de la machine.</p><p class="small muted" style="margin-top:10px">Les réponses et le chrono restent dans cet onglet pendant la session. Fermer l’onglet peut les effacer.</p><button class="text-link" id="open-sources">Voir toutes les sources ↗</button><br><button class="text-link" id="reset-session">Préparer une nouvelle séance</button></div>`);$('#open-sources').onclick=()=>showSources('all');$('#reset-session').onclick=()=>{openModal('NOUVELLE SÉANCE',`<h2 class="modal-title">Remettre l’atelier à zéro ?</h2><p class="body">Le chrono, les choix, les observations et ton idée dans cet onglet seront effacés.</p><div class="finish-actions"><button class="primary" id="reset-confirm">Réinitialiser la séance</button><button class="pill" id="reset-cancel">Garder cette séance</button></div>`);$('#reset-cancel').onclick=showGuide;$('#reset-confirm').onclick=()=>{state=JSON.parse(JSON.stringify(initial));save();closeModal();showIntro();tick();};};}
function tick(){const total=Math.floor(elapsed()/1000);$('#clock-text').textContent=total||state.runningSince?`${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`:'Démarrer';$('#clock').setAttribute('aria-label',state.runningSince?'Mettre en pause le chrono de l’atelier':'Démarrer ou reprendre le chrono de l’atelier');$('#clock').firstChild.textContent=state.runningSince?'Ⅱ ':'▷ ';}
$('#prev').onclick=()=>go(state.page-1);$('#next').onclick=()=>go(state.page+1);$('#home').onclick=()=>showIntro();$('#guide').onclick=showGuide;$('#close-modal').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
$('#clock').onclick=()=>{if(state.runningSince){state.elapsed=elapsed();state.runningSince=null;}else{state.runningSince=Date.now();}save();tick();};
document.addEventListener('keydown',e=>{if(document.body.classList.contains('intro-active'))return;if($('#modal').open||e.altKey||e.ctrlKey||e.metaKey||/^(INPUT|TEXTAREA|SELECT|CANVAS)$/.test(e.target.tagName)||e.target.isContentEditable)return;if(e.key==='ArrowRight'){e.preventDefault();go(state.page+1);}if(e.key==='ArrowLeft'){e.preventDefault();go(state.page-1);}});
window.addEventListener('hashchange',()=>{if(!location.hash||location.hash==='#intro'){showIntro(false);return;}const n=Number(location.hash.match(/^#etape-(\d+)$/)?.[1]);if(n>=1&&n<=9){document.body.classList.remove('intro-active');state.page=n-1;render(true);}});
const hashPage=Number(location.hash.match(/^#etape-(\d+)$/)?.[1]);if(hashPage>=1&&hashPage<=9)state.page=hashPage-1;
function showIntro(focus=true){stopLayerAnimation();document.body.classList.add('intro-active');history.replaceState(null,'','#intro');window.scrollTo({top:0,behavior:'instant'});if(focus)$('#intro-title').focus({preventScroll:true});}
$('#enter-workshop').onclick=()=>{state.scenario=0;go(0);};
render();if(hashPage>=1&&hashPage<=9)document.body.classList.remove('intro-active');else showIntro(false);
tick();setInterval(tick,1000);

// Optional browser-native agent access, sharing the visible workshop state.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'read_workshop_state',description:'Read the current workshop step and selected model. Does not read or control a printer.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return {step:state.page+1,title:plan[state.page][0],object:state.object};}});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
